### ISSUE TITLE
A problem about the input tensor.

### ISSUE THREAD

**Issue by fourierer** [nmhkahn/torchsummaryX#13]
Hello, I wanna use this tool to calculate params and flops of GhostNet model, which is proposed in CVPR2020. I met an error when I set different input tensors. 
(1)
`summary(model, torch.zeros(2, 3, 224, 224))`
It can work correctly;
(2)
`summary(model, torch.zeros(1, 3, 224, 224))`
There is an error "ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 1280])"
Is this normal? Does it calculate the params and the flops correctly when I set the N to 2?

**Comment by nmhkahn** [comment]
Hi. It because nn.BatchNorm1d does not accept batch_size=1 on the training phase.
If you first call `.eval()` then I guess it works.

**Comment by fourierer** [comment]
> Hi. It because nn.BatchNorm1d does not accept batch_size=1 on the training phase.
> If you first call `.eval()` then I guess it works.

Thank you so much for your reply！
